spring.application.name=mediflow-backend

# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mediflow}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# =========================================================
# SERVER
# =========================================================

server.port=${PORT:8080}

# =========================================================
# GEMINI
# =========================================================

gemini.api.key=${GEMINI_API_KEY}

# =========================================================
# JWT
# =========================================================

jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}

# =========================================================
# SWAGGER / OPENAPI
# =========================================================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
